### ISSUE TITLE
Collect issues related to Release Management from across the project

### ISSUE THREAD

**Issue by hdamker** [camaraproject/ReleaseManagement#2]
**Problem description**

This working group was created by the TSC to focus the work on Release Management topics across all sub projects of CAMARA. As a first step the open issues related to Release Management should be transfered to this working group.

**Expected action**

- [x] Transfer https://github.com/camaraproject/ReleaseManagement/issues/9 from Commonalities
- [x] Transfer https://github.com/camaraproject/ReleaseManagement/issues/4 from Governance
- [x] Ask Commonalities to transfer further issues, e.g. the ones listed in https://github.com/camaraproject/ReleaseManagement/issues/9

**Additional context**

Based on the transfered issues maybe new/further issues have to be created.

**Comment by hdamker** [comment]
All issues labeled as "release management" in Commonalities are transferred into the sub project here. Links to the issues seem to be automatically updated 😄
